name: Checking
on: 
  push:
  pull_request:
  
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythoon-versions: ["3.9", "3.10"]
    steps:
    - uses : actions/checkout@v3
    - name : Set up python ${{matrix.python-version}}
      uses: actions/seup/setup-python@v4
      with:
        python-version: ${{matrix.python-version}}
    - name: Checking
      run: 
        python -m pip install --upgrade pip
        python -m pip install tox
        tox
    
